cmake_minimum_required(VERSION 3.16)
project(hipnuc_serial C)
if(NOT TARGET hipnuc_core)
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../hipnuc hipnuc EXCLUDE_FROM_ALL)
endif()
add_library(hipnuc_serial STATIC hipnuc_serial.c serial_io.c)
target_include_directories(hipnuc_serial PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(hipnuc_serial PUBLIC hipnuc_core)
set_target_properties(hipnuc_serial PROPERTIES C_STANDARD 99 C_STANDARD_REQUIRED YES)
if(MSVC)
    target_compile_options(hipnuc_serial PRIVATE /W4)
else()
    target_compile_options(hipnuc_serial PRIVATE -Wall -Wextra)
endif()
