# Configure an actual C-only customer project and build the isolated CAN target.
file(MAKE_DIRECTORY "${WORK}/consumer")
file(WRITE "${WORK}/consumer/CMakeLists.txt" "cmake_minimum_required(VERSION 3.16)
project(customer C)
add_subdirectory(\"${SDK}\" hipnuc)
if(TARGET read_c OR TARGET read_cpp OR TARGET hipnuc_serial OR TARGET test_decoder)
  message(FATAL_ERROR \"Optional desktop code leaked into the customer build\")
endif()
get_property(languages GLOBAL PROPERTY ENABLED_LANGUAGES)
if(\"CXX\" IN_LIST languages)
  message(FATAL_ERROR \"C-only integration enabled C++\")
endif()
foreach(module hipnuc_json hipnuc_j1939)
  get_target_property(dependencies \${module} LINK_LIBRARIES)
  if(NOT dependencies STREQUAL \"hipnuc_sample\")
    message(FATAL_ERROR \"CAN/JSON unexpectedly depend on serial decoding\")
  endif()
endforeach()
add_executable(customer \"${SDK}/tests/consume_can.c\")
target_link_libraries(customer PRIVATE hipnuc_j1939 hipnuc_json)
")
set(platform_args)
if(NOT "${PLATFORM}" STREQUAL "")
    list(APPEND platform_args -A "${PLATFORM}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${WORK}/consumer" -B "${WORK}/build"
    -G "${GENERATOR}" ${platform_args} "-DCMAKE_C_COMPILER=${COMPILER}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Customer configure failed:\n${output}\n${errors}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${WORK}/build" --config Release
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Customer build failed:\n${output}\n${errors}")
endif()
