foreach(scene stream interrupt open_error)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env "HIPNUC_EXAMPLE_SCENE=${scene}" "${BINARY}"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE diagnostic TIMEOUT 5)
    if(scene STREQUAL "open_error")
        if(NOT status EQUAL 1 OR diagnostic MATCHES "TEST_CLOSED" OR NOT output STREQUAL "")
            message(FATAL_ERROR "Open failure contract: ${status}\n${output}\n${diagnostic}")
        endif()
    else()
        if(scene STREQUAL "interrupt")
            set(expected 130)
            set(warnings 1)
        else()
            set(expected 1)
            set(warnings 2)
        endif()
        string(REGEX MATCHALL "No valid sample" notices "${diagnostic}")
        list(LENGTH notices count)
        if(NOT status EQUAL expected OR NOT count EQUAL warnings OR
           NOT diagnostic MATCHES "Connected" OR NOT diagnostic MATCHES "Data resumed" OR
           NOT diagnostic MATCHES "TEST_CLOSED" OR NOT output MATCHES "roll/pitch\\(rad\\)=0.25.*-0.5")
            message(FATAL_ERROR "Read/recovery contract: ${status}\n${output}\n${diagnostic}")
        endif()
    endif()
endforeach()
