cmake_minimum_required(VERSION 3.16)
project(hipnuc_examples C CXX)
if(NOT TARGET hipnuc_serial)
    add_subdirectory(../serial serial)
endif()
add_executable(read_c read.c)
add_executable(read_cpp read.cpp)
target_link_libraries(read_c PRIVATE hipnuc_serial)
target_link_libraries(read_cpp PRIVATE hipnuc_serial)
set_target_properties(read_c PROPERTIES C_STANDARD 99 C_STANDARD_REQUIRED YES)
set_target_properties(read_cpp PROPERTIES CXX_STANDARD 11 CXX_STANDARD_REQUIRED YES)
