#hipnuc config
serial_port: "/dev/ttyUSB1"
baud_rate: 115200                    #default: 115200
frame_id: "gnss_link"
imu_topic: "/rawimu_data"
gps_topic: "/NavSatFix_data"
ins_topic: "/GPSFix_data"
gst_topic: "/GPSStatus_data"


