cmake_minimum_required(VERSION 3.16)
project(hipnuc_serial_update C)
if(NOT TARGET hipnuc_serial)
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../../serial serial)
endif()
if(NOT TARGET hipnuc_tool_common)
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../common common)
endif()
add_executable(hipnuc-update main.c)
if(MINGW)
    enable_language(RC)
    target_sources(hipnuc-update PRIVATE application.rc)
    target_include_directories(hipnuc-update PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
endif()
target_link_libraries(hipnuc-update PRIVATE hipnuc_serial hipnuc_update hipnuc_tool_common)
set_target_properties(hipnuc-update PROPERTIES C_STANDARD 99 C_STANDARD_REQUIRED YES)
if(MSVC)
    target_compile_options(hipnuc-update PRIVATE /W4)
else()
    target_compile_options(hipnuc-update PRIVATE -Wall -Wextra)
endif()
