canImuPublisher:
    ros__parameters:
        can_port: "can0"
        baud_rate: 500000
        node_id: 8
        frame_id: "imu_link"
        imu_switch: FALSE
        imu_topic_canopen: "/imu/canopen_msg"
        imu_topic_j1939: "/imu/j1939_msg"
        euler_switch: FALSE
        euler_topic_canopen: "/euler/canopen_msg"
        euler_topic_j1939: "/euler/j1939_msg"
        mag_switch: FALSE
        mag_topic_j1939: "/mag/j939_msg"
        sub_topic: "/imu/canopen_msg"


